services:
  router:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - './nginx:/etc/nginx/conf.d/'
    depends_on:
      - api
      - frontend
    networks:
     - pdqnet
  api:
    image: simplemdm-toybox-api
    tty: true
    environment:
      - PORT=4100
    command: ["rails", "s", "-b", "0.0.0.0", "-p", "4100"]
    volumes:
      - './api:/var/www/api'
    networks:
      - pdqnet
    depends_on:
      - db
  frontend:
    image: node:22-alpine
    working_dir: '/var/www/frontend'
    command: ["yarn", "dev"]
    depends_on:
      - api
    volumes:
      - './frontend:/var/www/frontend'
    networks:
      - pdqnet
  db:
    image: mysql/mysql-server:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 4103:3306
    volumes:
      - simplemdm_toybox_dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"
    networks:
      - pdqnet
volumes:
  simplemdm_toybox_dbdata:
networks:
  pdqnet:
    attachable: true
