version: '3.8'
services:
  api:
    image: pdq-interview-rails
    tty: true
    ports:
      - 3000:3000
    volumes:
      - './rails:/var/www/rails'
    networks:
      - pdqnet
    depends_on:
      - db
#  frontend:
#    environment:
#      - PORT=4000
#    image:
#    command: yarn dev
#    tty: true
#    depends_on:
#      - api
#    ports:
#      - 4000:4000
#      - 9292:9292
#    volumes:
#      - './frontend:/var/www/rails'
#    networks:
#      - pdqnet
  db:
    image: mysql/mysql-server:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3307
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"
    networks:
      - pdqnet
volumes:
  dbdata:
networks:
  pdqnet:
    attachable: true
