version: '3.8'
services:
  api:
    image: pdq-interview-api
    tty: true
    environment:
      - PORT=4100
    ports:
      - 4100:4100
    command: ["rails", "s", "-b", "0.0.0.0", "-p", "4100"]
    volumes:
      - './api:/var/www/api'
    networks:
      - pdqnet
    depends_on:
      - db
  frontend:
    environment:
      - PORT=5001
    image: pdq-interview-frontend
    command:
      - yarn dev
    tty: true
    depends_on:
      - api
    ports:
      - 4101:4000
      - 4102:9292
    volumes:
      - './frontend:/var/www/frontend'
    networks:
      - pdqnet
  db:
    image: mysql/mysql-server:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 4103:3306
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"
    networks:
      - pdqnet
volumes:
  dbdata:
networks:
  pdqnet:
    attachable: true
