import type {AppProps} from 'next/app'
import Head from "next/head";
import Layout from "@/components/layout";
import {Container, ThemeProvider} from "@mui/material";
import CssBaseline from "@mui/material/CssBaseline";
import theme from '../styles/theme'

export default function App({Component, pageProps}: AppProps) {
    return <ThemeProvider theme={theme}>
        <Head>
            <title>SimplerMDM</title>
            <meta name="description" content="Generated by create next app"/>
            <meta name="viewport" content="width=device-width, initial-scale=1"/>
            <link rel="icon" href="/favicon.png"/>
            <link rel="stylesheet"
                  href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"/>
            <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons"/>
        </Head>
        <CssBaseline/>
        <Layout>
            <Container>
                <Component {...pageProps} />
            </Container>
        </Layout>
    </ThemeProvider>
}
