import type {AppProps} from 'next/app'
import Layout from "@/components/layout";
import {Container, ThemeProvider} from "@mui/material";
import CssBaseline from "@mui/material/CssBaseline";
import theme from '../styles/theme'
import Head from "next/head";

export default function App({Component, pageProps}: AppProps) {
    return <ThemeProvider theme={theme}>
        <Head>
            <title>SimplerMDM</title>
            <meta name="description" content="Generated by create next app"/>
            <meta name="viewport" content="width=device-width, initial-scale=1"/>
        </Head>

        <CssBaseline/>
        <Layout>
            <Container>
                <Component {...pageProps} />
            </Container>
        </Layout>
    </ThemeProvider>
}
