import {Html, Head, Main, NextScript} from 'next/document'
import CssBaseline from '@mui/material/CssBaseline';
import {Grid} from "@mui/material";
import Sidebar from "@/components/sidebar";

export default function Document() {
    return (
        <Html lang="en">
            <CssBaseline/>
            <Head>
                <title>SimplerMDM</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.png"/>
                <link rel="stylesheet"
                      href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"/>
                <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons"/>
            </Head>
            <body>
            <Grid container spacing={1}>
                <Grid item xs={3}>
                    <Sidebar/>
                </Grid>
                <Grid item xs={9}>
                    <Main/>
                </Grid>
            </Grid>
            <NextScript/>
            </body>
        </Html>
    )
}
