import Head from 'next/head'
import Button from '@mui/material/Button';

export default function Home() {
  return (
    <>
      <Head>
        <title>SimplerMDM</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" />
      </Head>

      <main>
        <Button variant="contained">Hello World</Button>
      </main>
    </>
  )
}
